[IA-528] Support message category
pagopa/io-dev-api-server pull request #100
Opened 2021-12-02 09:00 UTC by pietro909

2021-12-13 08:46 UTC, Undermaken requested changes

2021-12-13 09:26 UTC, pietro909 commented on src/payloads/message.ts
> +  const senderService = services.find(
This being the dev-server (no perf concerns), I wouldn't mind about extra iterations.

Consider also that with MVL we'll eventually have to cross-reference more information for new categories.

2021-12-13 09:31 UTC, pietro909 commented on src/payloads/message.ts
> +      rptId: `${senderService.organization_fiscal_code}${payment_data.notice_number}`
Good idea!
See https://github.com/pagopa/io-dev-api-server/pull/100/commits/ceb685de2e7b7adedd98355c4865a2929fd8506f

2021-12-14 08:07 UTC, Undermaken approved these changes

2021-12-14 08:08 UTC, merged