[IAMVL-14] Support Legal message category and details
pagopa/io-dev-api-server pull request #107
Opened 2021-12-17 13:56 UTC by pietro909

2021-12-20 12:33 UTC, Undermaken requested changes

2021-12-20 12:33 UTC, Undermaken commented on src/payloads/message.ts
> +  if ((message as LegalMessageWithContent).legal_message) {
```suggestion
  if (LegalMessageWithContent.decode(message).isRight()) {
```
pretty the same but using the dedicated codec

2021-12-20 12:33 UTC, Undermaken commented on src/payloads/message.ts
> +    return {
As you know I like the pattern matching
I tried to convert these if/else statements using it
This is the result

```typescript
  return match(message)
    .when(
      m => LegalMessageWithContent.decode(m).isRight(),
      () => ({
        tag: TagEnumBase.LEGAL_MESSAGE
      })
    )
    .with(
      {
        content: {
          eu_covid_cert: not(__.nullish)
        }
      },
      () => ({
        tag: TagEnumBase.EU_COVID_CERT
      })
    )
    .with(
      {
        content: {
          payment_data: not(__.nullish)
        }
      },
      m => ({
        tag: TagEnumPayment.PAYMENT,
        rptId: getRptID(senderService, m.content.payment_data)
      })
    )
    .otherwise(() => ({
      tag: TagEnumBase.GENERIC
    }));
};
```
Feel free to skip it

2021-12-20 17:27 UTC, Undermaken requested changes

2021-12-20 17:27 UTC, Undermaken commented on src/routers/message.ts
> +    // }
could it be removed?

2021-12-20 17:27 UTC, Undermaken commented on src/routers/message.ts
> +      res.json(getProblemJson(404, "message not found"));
```suggestion
      res.json(getProblemJson(404, "message not found"));
      return;
```

2021-12-20 17:27 UTC, Undermaken commented on src/routers/message.ts
> +    res.json(message);
Should we also check that the request message is a legal message?
```suggestion
    if (LegalMessageWithContent.decode(message).isLeft()) {
      res.json(getProblemJson(400, "bad parameter"));
      return;
    }
    res.json(message);
```

2021-12-20 18:45 UTC, Undermaken requested changes

2021-12-20 18:45 UTC, Undermaken commented on src/payloads/message.ts
> +        msg_id: "fghi" as NonEmptyString,
```suggestion
        msg_id: `mvl_${message.id}` as NonEmptyString,
```
Maybe we should not use a fixed id for all MVL messages.

2021-12-21 15:50 UTC, pietro909 commented on src/payloads/message.ts
> +    return {
I love pattern matching too, though it is not supported by the language therefore I'd rather use something more idiomatic like truthy checks and early returns.

2021-12-21 15:56 UTC, pietro909 commented on src/routers/message.ts
> +    res.json(message);
It's a good observation, though I don't know how the API would respond in this case.
Maybe @fabriziopapi can answer this question.

2021-12-21 15:59 UTC, pietro909 commented on src/routers/message.ts
> +    // }
I left it there for [future use](https://github.com/pagopa/io-dev-api-server/pull/107/files#diff-c4cdb7cf0e69ecfc696d0ba80b8411dd4297658be4a57dad5f0954d7a9ae6d74R448). Now is working 🎉

2021-12-21 20:18 UTC, Undermaken requested changes

2021-12-21 20:18 UTC, Undermaken commented on src/routers/message.ts
> +    res.json(message);
We already know what this API returns in case of `200`
https://github.com/pagopa/io-backend/blob/df2c4bb5a62df3ce2f9254c04ca56bae18032032/api_backend.yaml#L280
I believe we should ensure that from the given id we are actually returning a legal message detail

2021-12-22 09:57 UTC, pietro909 commented on src/routers/message.ts
> +    res.json(message);
I think we are overthinking it: if the point of the dev-server is to mimick the actual API, we must know how it would behave if a client asked for an ID which is a message but not a _legal_ one.
Otherwise, 404 is totally fine in my opinion.

2021-12-22 10:46 UTC, pietro909 commented on src/routers/message.ts
> +    res.json(message);
Updated in https://github.com/pagopa/io-dev-api-server/pull/107/commits/4373e149d34a0d2d4b754b8b0e1e370ea9b25777 as per our chat. Now returning a meaningful message which will help us during development.

2021-12-22 12:01 UTC, Undermaken commented
This PR will be included in https://github.com/pagopa/io-dev-api-server/pull/108

2021-12-22 12:01 UTC, closed without merging