Implements handler for special services activation
pagopa/io-dev-api-server pull request #115
Opened 2022-01-07 15:48 UTC by CrisTofani

This PR aims to properly handle the special services activation status. 
CGN activation now effects the related service activation

2022-01-12 10:22 UTC, pietro909 commented on src/payloads/services/index.ts
> +        const specialServiceInbox = fromNullable(metadata.custom_special_flow)
It seems like `specialServiceInbox` is a boolean: maybe `hasSpecialServiceInbox` would better convey this semantics?

2022-01-13 14:12 UTC, Undermaken requested changes

2022-01-13 14:12 UTC, Undermaken commented on src/payloads/services/index.ts
> +              ? faker.datatype.boolean()
```suggestion
              ? getRandomValue(false, faker.datatype.boolean(), "services")
```
we are trying to dominate the randomness in the dev-server with the configuration
A dev could go crazy if a value change on every request :dizzy_face:

2022-01-13 14:12 UTC, Undermaken commented on src/routers/features/cgn/index.ts
> +        : (0 as ServicePreference["settings_version"]);
```suggestion
      const increasedSettingsVersion = ((currentPreference?.settings_version ??
        -1) + 1) as NonNegativeInteger;
```
the same, shorter but less readable. On your flavor

2022-01-13 14:12 UTC, Undermaken commented on src/routers/features/cgn/index.ts
> +        is_email_enabled: faker.datatype.boolean(),
```suggestion
        is_email_enabled:currentPreference?.is_email_enabled ??
          getRandomValue(false, faker.datatype.boolean(), "services"),
```
the same of the other part: we should avoid the dev madness with a value that could change on every API invocation

2022-01-13 14:52 UTC, Undermaken requested changes

2022-01-13 14:52 UTC, Undermaken commented on src/payloads/services/index.ts
> +              ? faker.datatype.boolean()
```suggestion
              ? getRandomValue(false, faker.datatype.boolean(), "services")
```

2022-01-13 15:16 UTC, Undermaken approved these changes

2022-01-13 15:16 UTC, merged