[IAC-139] Update BPS citizenV2 GET/PUT API
pagopa/io-dev-api-server pull request #137
Opened 2022-02-03 16:56 UTC by Undermaken

2022-02-08 18:09 UTC, debiff requested changes

2022-02-08 18:09 UTC, debiff commented on src/routers/features/bdp/__tests__/index.test.ts
> +  it("Should return a 200, CitizenResource (V2) with optInStatus update", async () => {
The test looks good, but if I change the order of the tests, or if I execute it in isolation, it fails.

Maybe we can group the tests that need the same status under a `describe` and use the `beforeEach` function to lead to the right status?

2022-02-08 18:14 UTC, Undermaken commented on src/payloads/backend.ts
> +      program_active: true,
🦅 
good catch

2022-02-08 18:22 UTC, Undermaken commented on src/routers/features/bdp/__tests__/index.test.ts
> +  it("Should return a 200, CitizenResource (V2) with optInStatus update", async () => {
You hit my laziness, thank you
refactored here 
https://github.com/pagopa/io-dev-api-server/pull/137/commits/50a8bdd0c77cbf4a2a514d38e355d9d466883851
![Schermata 2022-02-08 alle 19 20 47](https://user-images.githubusercontent.com/822471/153051334-823d703c-1b32-4fa0-bec1-ad55dd292ff7.png)

2022-02-09 11:03 UTC, debiff approved these changes

2022-02-09 11:04 UTC, merged