[IA-678] Support archived and read status server side
pagopa/io-dev-api-server pull request #143
Opened 2022-03-01 15:44 UTC by pietro909

## Short description
Introduce a new endpoint to mark messages as read or archived. Persist the information on the server.

## List of changes proposed in this pull request

## How to test

2022-03-18 15:41 UTC, Undermaken requested changes

2022-03-18 15:41 UTC, Undermaken commented on src/persistence/messages.ts
> +  return inboxMessages as ReadonlyArray<MessageOnDB>;
```suggestion
  return inboxMessages;
```
maybe it is no need since it is declared in the return type

2022-03-18 15:41 UTC, Undermaken commented on src/persistence/messages.ts
> +  return archivedMessages as ReadonlyArray<MessageOnDB>;
```suggestion
  return archivedMessages;
```
same of above

2022-03-18 15:41 UTC, Undermaken commented on src/persistence/messages.ts
> +  );
```suggestion
  return (
    [...inboxMessages, ...archivedMessages].find(
      message => message.id === id
    ) ?? null
  );
```
pretty the same, choose to your taste
PS: if you return undefined (as `find` already does) we can avoid the _nullish coalescing_

2022-03-18 15:41 UTC, Undermaken commented on src/populate-persistence.ts
> +  customConfig: IoDevServerConfig,
if you want you can avoid this parameter since the config is available as object from everywhere 
`ioDevServerConfig`

2022-03-18 15:41 UTC, Undermaken commented on src/populate-persistence.ts
> +};
```suggestion
const getServiceId = (): string => {
  if (services.length === 0) {
    throw new Error(
      "to create messages, at least one sender service must exist!"
    );
  }
  return getRandomValue(
    services[0].service_id,
    faker.random.arrayElement(services).service_id,
    "messages"
  );
};
```
to make the global config more efficient, could be a good idea to return a random `serviceId` only when the randomness is enabled for this specific section (`messages`)?

2022-03-18 15:41 UTC, Undermaken commented on src/populate-persistence.ts
> +    output.push(medicalMessage(count));
```suggestion
```
double push

2022-03-22 08:58 UTC, pietro909 commented on src/persistence/messages.ts
> +  );
I'd keep the `null` because it reflects how (some) SQL databases work.
No real opinions on the rest, just tell me if you want me to change it.

2022-03-22 09:02 UTC, pietro909 commented on src/populate-persistence.ts
> +};
No opinions from my side: is a testing tool and I see no value in performance tuning.
Your call 😃

2022-03-22 16:42 UTC, Undermaken commented on src/populate-persistence.ts
> +};
What I meant with `Efficient` is not about performance but to make the dev-server deterministic (or with a certain degree of randomness) by configuration. 

As you can see each sections of the configuration (messages, profile, services etc..) has an optional flag `allowRandomValue` . This is useful in dev-environment (or in automatic e2e tests) when you want to load always the same data and avoid randomness.

2022-03-22 16:46 UTC, Undermaken requested changes
To avoid dangerous type casting (`any` and `unknown`) I tried, in a dedicated branch, to refactor some types and it seems to work
4b83e1677b673fca331880c67912ba1ef75bd41b
What do you think?

2022-03-25 09:55 UTC, pietro909 commented on src/populate-persistence.ts
> +};
Got it. I was misled by _efficient_.

2022-03-25 09:56 UTC, pietro909 commented
@Undermaken if it compiles and feels safer, just commit it 😄

2022-03-25 10:44 UTC, Undermaken approved these changes

2022-03-25 10:44 UTC, merged