[IAI-249] Update README instructions to include API definitions generation
pagopa/io-dev-api-server pull request #188
Opened 2022-10-13 09:22 UTC by Vangaorth

## Short description
This PR adds a missing instruction point to the Setup section in the README file. Such point is the API definition generation, after the `yarn install` command.

## List of changes proposed in this pull request
- Added the API definitions generation instruction and command on the SETUP section of the README file

## How to test
Follow the Setup process after repository cloning

2022-10-13 09:27 UTC, CrisTofani requested changes

2022-10-13 09:27 UTC, CrisTofani commented on README.MD
> +1. generate API definitions:
```suggestion
1. generate API definitions:<br/>
```
Just adding a break to make it look similar to the other points 🙂

2022-10-13 09:59 UTC, Vangaorth commented on README.MD
> +1. generate API definitions:
Is it possibile that the <br/>-s  are misplaced here? They seem to be ignored when displayed and other lists do not have them (e.g, the Docker Setup below). If this is the case, I would proceed by removing them all

2022-10-13 10:11 UTC, CrisTofani commented on README.MD
> +1. generate API definitions:
They're actually not ignored 😄 
That's how it looks like on Github the preview
![image](https://user-images.githubusercontent.com/3959405/195568322-9cbdbba5-8676-4caa-89e4-03c6822b84b1.png)

without the `<br/>` block it is represented on the single line, anyway we could rewrite this as an entire code block 🤔 

For example: 

```
# 1. clone this repository
$ git clone git@github.com:pagopa/io-dev-api-server.git
# 2. install all packages needed
$ yarn install
# 3. generate API definitions: 
$ yarn generate:all
# 4. you are ready! start the server:
$ yarn start
```

What do you think?

2022-10-13 11:01 UTC, Vangaorth commented on README.MD
> +1. generate API definitions:
While the suggested code-block approach sounds interesting, I would prefer to add the missing `<br/>` since:
- the not-ignored `<br/>` was a mistaken assumption of mine 
- consistency would require us to rewrite any list using the code-block
- existing lists are auto-enumerated, while the code-block requires further investigation to do so

So, if it is good for you, I will proceed with the missing `<br/>`

2022-10-13 11:33 UTC, CrisTofani commented on README.MD
> +1. generate API definitions:
Lgtm to add the break 😉

2022-10-20 08:06 UTC, francescopersico approved these changes

2022-10-21 12:38 UTC, CrisTofani approved these changes

2022-10-21 12:38 UTC, merged