[SFEQS-1080] Add FCI api specs
pagopa/io-dev-api-server pull request #189
Opened 2022-10-18 13:49 UTC by hevelius

### This PR depends on #185 

## Short description
This PR adds api specs for FCI

## List of changes proposed in this pull request
* added remote ref for fci api specs
* updated package.json and codegen scripts

2022-10-19 15:36 UTC, francescopersico requested changes

2022-10-19 15:37 UTC, francescopersico requested changes

2022-10-19 15:37 UTC, francescopersico commented on package.json
> +  "api_fci": "assets/fci/io-sign.yml",
Why are we using a local definition file instead of a reference to a repo?

2022-10-20 08:07 UTC, hevelius commented on package.json
> +  "api_fci": "assets/fci/io-sign.yml",
Like CDC I'll move the `fci` definitions in io-app repo. Unfortunately the dev-server uses an older version of generator that not support openapi > 3.x. This local file is a converted version in swagger 2.0 of this https://github.com/pagopa/io-functions-sign/blob/OpenApi-App-SFEQS-726/docs/openapi-backend.yaml

2023-01-13 09:42 UTC, merged