[SFEQS-1082] added fci endpoints
pagopa/io-dev-api-server pull request #190
Opened 2022-10-19 13:42 UTC by hevelius

### This PR depends on #189 

## Short description
This PR adds FCI endpoints and mocked payload

## List of changes proposed in this pull request
* updated package.json adding ulid (in FCI `ulid` is used as format)
* added routers and an initial test file
* added payload to mock responses

2022-10-19 14:09 UTC, gunzip commented on assets/fci/io-sign.yml
> +      - documentSignatures
we don't need these

2022-10-19 14:09 UTC, gunzip commented on assets/fci/io-sign.yml
> +      spidSamlAssertion:
we don't need these here

2022-10-19 14:51 UTC, gunzip commented on assets/fci/io-sign.yml
> +info:
you need to add a security section: https://github.com/pagopa/io-backend/blob/master/api_backend.yaml#L10

2022-10-19 14:51 UTC, gunzip commented on assets/fci/io-sign.yml
> +swagger: "2.0"
may you move this line at the beginning?

2023-03-09 08:11 UTC, shadowsheep1 requested changes

2023-03-09 08:11 UTC, shadowsheep1 commented on config/config.json
> +    "withCTA": true
Did you test if adding this kind of messages it won't break the E2E test?

2023-03-09 08:11 UTC, shadowsheep1 commented on package.json
> +  "api_fci": "https://raw.githubusercontent.com/pagopa/io-backend/60c472552814b6815ea146ca18ddfe579f671452/api_io_sign.yaml",
Aren't fci specs now in production? Do we have a tag to use or we must still point to a specific branch or commit?

2023-03-09 08:11 UTC, shadowsheep1 commented on src/payloads/features/fci/signature-request.ts
> +const basePath = "http://127.0.0.1:3000";
Why don't you use `serverUrl` from [here](https://github.com/pagopa/io-dev-api-server/blob/ddf29ed78a3707ad0498b12e8d806c4108d736b2/src/utils/server.ts#L43)

2023-03-09 08:55 UTC, hevelius commented on config/config.json
> +    "withCTA": true
Which 2e2 tests? `withCTA` is not a kind of message but a config value used to populate the message list

2023-03-09 10:04 UTC, shadowsheep1 requested changes

2023-03-09 10:04 UTC, shadowsheep1 commented on config/config.json
> +    "withCTA": true
Well we use this [custom config](https://github.com/pagopa/io-app/blob/c5a0af370a5629584e6cdc2bae533326466c04cf/scripts/api-config.json#L18) to run E2E tests, and it's set to `true` so this won't impact. Anyway just to ask, you are adding, at the end of the list, FCI messages. Did you double check not to brake E2E tests?

2023-03-09 10:25 UTC, shadowsheep1 requested changes

2023-03-09 10:25 UTC, shadowsheep1 commented on src/populate-persistence.ts
> +    );
Should we add a guard with a custom config as we did for other kinds of messages?

For example:

```
 customConfig.messages.medicalCount > 0 &&
    range(1, customConfig.messages.medicalCount).forEach(count => {
      const baseMessage = medicalMessage(count);
      const attachments: ReadonlyArray<MessageAttachment> = [
        {
          name: "prescription A",
          content: "up, down, strange, charm, bottom, top",
          mime_type: "text/plain"
        },
        {
          name: "prescription B",
          content: barcodeReceipt,
          mime_type: "image/svg+xml"
        }
      ];
      output.push({
        ...baseMessage,
        content: {
          ...baseMessage.content,
          subject: `💊 medical prescription with attachments - ${count}` as MessageSubject,
          attachments
        }
      });
    });
```

2023-03-09 14:46 UTC, shadowsheep1 approved these changes
LGTM

2023-03-09 15:03 UTC, merged