[LLK-58] Http-Signature Verification
pagopa/io-dev-api-server pull request #214
Opened 2023-03-08 13:28 UTC by shadowsheep1

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-03-08 13:37 UTC, grausof commented on src/utils/httpSignature.ts
> +    A.head,
You can use `A.findFirst`

2023-03-08 13:37 UTC, shadowsheep1 commented on src/utils/__tests__/httpSignature.test.ts
> +"@signature-params": ("x-pagopa-lollipop-custom-sign-challenge");created=1677499068;nonce="nonceMockedBase64";alg="ecdsa-p256-sha256";keyid="cZHpXWy9TJ4AlV7uPSra4o6ojTel5wQPvWhJOui7Wb4"`;
Yep! You are right! And we have it indeed, in two flavor (functional and imperative [here](https://github.com/pagopa/io-dev-api-server/blob/304d1e9f3d8d6438b4da185a9e3034cfa50147ab/src/utils/httpSignature.ts#L24)). We have use a TDD approach and literals aims to validate the function itself in tests.  When this PR will shift from draft to ready probably one of the two functions will be removed (the imperative one I suppose).

2023-03-08 13:48 UTC, shadowsheep1 commented on src/utils/httpSignature.ts
> +    A.head,
Yup but I need the `index` for the filtering condition. Or I could find a way to have a `regex` filtering condition like with `replace` few lines below .

2023-03-08 16:03 UTC, shadowsheep1 commented on src/utils/httpSignature.ts
> +    A.head,
Done ;)

2023-03-09 14:21 UTC, hevelius requested changes

2023-03-09 14:21 UTC, hevelius commented on src/utils/__tests__/httpSignatureEC.test.ts
> +  it("test FCI custom content to sign (imperative)", async () => {
```suggestion
  it("Test FCI custom content to sign (imperative)", async () => {
```

2023-03-09 14:21 UTC, hevelius commented on src/utils/__tests__/httpSignatureEC.test.ts
> +  it("test FCI custom content to sign (fp-ts)", async () => {
```suggestion
  it("Test FCI custom content to sign (fp-ts)", async () => {
```

2023-03-09 14:21 UTC, hevelius commented on src/utils/__tests__/httpSignatureEC.test.ts
> +    const pemKey = await toPem(ecPublicKeyJwk);
What do you think about using fp-ts also in test? This could be a TE and should be tested using expect and pipe. https://github.com/pagopa/io-sign/blob/main/packages/io-sign/src/__test__/document.spec.ts

2023-03-09 14:21 UTC, hevelius commented on src/utils/__tests__/httpSignatureRSA.test.ts
> +  it("test JWK thumbprint", async () => {
```suggestion
  it("Test JWK thumbprint", async () => {
```

2023-03-09 14:21 UTC, hevelius commented on src/utils/__tests__/httpSignatureRSA.test.ts
> +describe("suite to test the http signature verification utility", () => {
```suggestion
describe("Suite to test the http signature verification utility", () => {
```

2023-03-09 14:21 UTC, hevelius commented on src/utils/__tests__/httpSignatureRSA.test.ts
> +  it("Verify tos challenge signature", async () => {
Should be the first char uppercase?

2023-03-09 14:21 UTC, hevelius commented on src/utils/httpSignature.ts
> +    }),
I think should works

```suggestion
    A.findFirst(new RegExp(`^sig\\d+=\\("${headerName}"\\)`).test),
```

2023-03-10 11:37 UTC, SabPicariello commented on src/utils/httpSignature.ts
> +    }),
Apparently it doesn't work without specifying "value"

2023-03-10 14:36 UTC, hevelius requested changes

2023-03-10 14:36 UTC, hevelius commented on src/utils/__tests__/httpSignatureEC.test.ts
> +  it("Test JWK thumbprint", async () => {
Looking at the typical format for test descriptions, I believe they should be written as follows:
"with X should be greater of Y" or "giving an array of X should be equale to Y"
What do you think about this?

2023-03-13 15:10 UTC, hevelius requested changes

2023-03-13 15:10 UTC, hevelius commented on src/utils/__tests__/httpSignature/ec.test.ts
> +describe("Test FCI custom content TOS and Sign Challenges", () => {
Why is there a test for FCI feature? I suggest to move this under `fci` folder.

2023-03-13 15:10 UTC, hevelius commented on src/utils/__tests__/httpSignature/ec.test.ts
> +    it(`Test that we retrive a valid sign algorithm for "${content.header}" from signature-input`, () => {
What do you think about write test description like: `it should retrive a valid sign algorithm for ....`
```suggestion
    it(`it should retrive a valid sign algorithm for "${content.header}" from signature-input`, () => {
```

2023-03-13 15:10 UTC, hevelius commented on src/utils/__tests__/httpSignature/ec.test.ts
> +    };
What do you think about move this out of there at the top of file and write instead 
```suggestion
  ["sig1", "sig2", "sig3", undefined, "sig8"].forEach(signatureKey => {
    const mockRequestOptions: VerifySignatureHeaderOptions = {
      ...mockedRequest,
      signatureKey
    };
```

2023-03-13 15:10 UTC, hevelius commented on src/utils/__tests__/httpSignature/rsa.test.ts
> +describe("Test FCI custom content TOS and Sign Challenges", () => {
As above maybe this type of test related to a feature like FCI should be move to `fci` -> `featureX` folder

2023-03-15 09:37 UTC, shadowsheep1 commented on src/utils/__tests__/httpSignature/ec.test.ts
> +describe("Test FCI custom content TOS and Sign Challenges", () => {
Maybe it's better to change the suite title. Here we are testing the custom content signature (that for now is related to FCI) but it's a general feature provided by the lib.

2023-03-15 09:38 UTC, shadowsheep1 commented on src/utils/__tests__/httpSignature/ec.test.ts
> +    it(`Test that we retrive a valid sign algorithm for "${content.header}" from signature-input`, () => {
Yup, simply better!

2023-03-15 09:38 UTC, shadowsheep1 commented on src/utils/__tests__/httpSignature/ec.test.ts
> +    };
I agree.

2023-03-15 09:38 UTC, shadowsheep1 commented on src/utils/__tests__/httpSignature/rsa.test.ts
> +describe("Test FCI custom content TOS and Sign Challenges", () => {
As above.

2023-03-15 09:39 UTC, shadowsheep1 commented on src/utils/__tests__/httpSignatureEC.test.ts
> +  it("Test JWK thumbprint", async () => {
Let's change it.

2023-03-15 12:46 UTC, hevelius approved these changes
LGTM

2023-03-15 13:12 UTC, merged