[IOCOM-282] Fixing eslint errors and warnings
pagopa/io-dev-api-server pull request #264
Opened 2023-06-07 09:00 UTC by adelloste

## Short description
This PR fixes eslint errors and warnings for the IOCOM team.

2023-06-07 16:01 UTC, Vangaorth requested changes

2023-06-07 16:43 UTC, adelloste commented on src/payloads/services/factory.ts
> +  A.makeBy(count, count => {
Applied https://github.com/pagopa/io-dev-api-server/pull/264/commits/583d6a20dd406c0b5c024b571aba01ae3fec243f

2023-06-07 20:20 UTC, adelloste commented on src/payloads/services/factory.ts
> +      organizationStartIndex++;
I got you, you're right. I thought the change was not really relevant however I refactored restoring the old business-logic https://github.com/pagopa/io-dev-api-server/pull/264/commits/9769902d25f6c5a58fbc24e7ce6db6d8889fd38f

2023-06-08 10:56 UTC, adelloste commented on src/routers/message.ts
> +          ...message,
Changed https://github.com/pagopa/io-dev-api-server/pull/264/commits/fe8669c5575bbdde7ba144a4f0889a330634f22e

2023-06-08 10:57 UTC, adelloste commented on src/populate-persistence.ts
> +          customConfig.messages.pnCount,
Changed

2023-06-09 08:28 UTC, Vangaorth approved these changes
LGTM

2023-06-09 10:44 UTC, merged