Added fastLogin logic
pagopa/io-dev-api-server pull request #265
Opened 2023-06-09 08:08 UTC by SabPicariello

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-06-12 10:59 UTC, shadowsheep1 requested changes
I've requested some minor changes.

2023-06-12 10:59 UTC, shadowsheep1 commented on config/config.json
> +
Why do we have an empty space here? ;)

2023-06-12 10:59 UTC, shadowsheep1 commented on src/persistence/sessionInfo.ts
> +const generateNewLoginToken = () => faker.random.alphaNumeric(11).toUpperCase();
And what about third party tokens? Maybe we should regenerate them too, just to have a quick feedback they've changed too? What do you think?

2023-06-14 08:29 UTC, shadowsheep1 requested changes

2023-06-14 08:29 UTC, shadowsheep1 commented on src/utils/date.ts
> +  firstDate.getTime() - secondDate.getTime();
I'd use the absolute value to be firstDate/secondDate temporal reference agnostic... what do you think?

2023-06-14 08:35 UTC, SabPicariello commented on src/utils/date.ts
> +  firstDate.getTime() - secondDate.getTime();
you are absolutely right :+1:

2023-06-14 09:18 UTC, shadowsheep1 approved these changes
LGTM

2023-06-14 09:25 UTC, merged