chore: [IOPID-714,IOPID-670]: Discriminate currentProfile based on auth provider
pagopa/io-dev-api-server pull request #297
Opened 2023-09-01 14:31 UTC by shadowsheep1

The auth provider is taken from a custom header coming from the app

## Short description
Include a summary of the changes.

## List of changes proposed in this pull request
- Feature A
- Feature B

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2023-09-11 15:47 UTC, Vangaorth requested changes

2023-09-11 15:47 UTC, Vangaorth commented on src/persistence/sessionInfo.ts
> +  authenticationProvider: undefined
This way, we are changing the default behaviour for which, upon first startup, `io-dev-api-server` already has the capability of generating data with a valid profile.
Can we provide a default value instead of `undefined`, like
```
  loginType: LoginEnum.standard,
  authenticationProvider: "spid"
```
?

Maybe we can also change the type so it is never `undefined`?

2023-09-11 15:59 UTC, Vangaorth requested changes

2023-09-11 15:59 UTC, Vangaorth commented on src/routers/profile.ts
> +export let currentProfile: InitializedProfile = {} as InitializedProfile;
Should we also not export this? If we do not do it, the `getCurrentProfile` method can be ignored and the profile is accessed without the proper flow.

2023-09-12 08:30 UTC, shadowsheep1 commented on src/routers/profile.ts
> +export let currentProfile: InitializedProfile = {} as InitializedProfile;
Good point. Thank you.

2023-09-12 08:36 UTC, shadowsheep1 commented on src/routers/profile.ts
> +export let currentProfile: InitializedProfile = {} as InitializedProfile;
Fixed.

2023-09-12 09:58 UTC, merged