[IOCOM-686] Add message generation with remote content
pagopa/io-dev-api-server pull request #323
Opened 2023-11-27 16:34 UTC by adelloste

## Short description
This PR allows to generate messages with remote content.

## List of changes proposed in this pull request
- `src/config`: added configuration for messages with remote content
- `src/populate-persistence.ts`: added generation of messages with remote content (saved in-memory)
- `src/features/messages/persistence/messagesPayload.ts`: added `withRemoteContent` function that adds remote content to the message

## How to test
Run the server instance with different configurations and check that the payload returned by the `/messages/:id` and `/third-party-messages/:id` endpoints is correct

2023-11-28 16:31 UTC, Vangaorth requested changes

2023-11-28 16:31 UTC, Vangaorth commented on src/features/messages/persistence/messagesPayload.ts
> -      has_attachments: true
This flag is sent by the real backend, we should keep it and assign a proper value to it. 
We also need to add the `has_remote_content: boolean` flag.
What do you think?

2023-11-28 16:31 UTC, Vangaorth commented on src/features/messages/services/messagesService.ts
> -          const { content, is_read, is_archived, has_attachments } =
See previous comment on keeping this value, also with the new `has_remote_content`

2023-11-28 16:31 UTC, Vangaorth commented on src/features/messages/services/messagesService.ts
> -            has_attachments,
See previous comment on keeping this value, also with the new `has_remote_content`

2023-11-29 09:07 UTC, adelloste commented on src/features/messages/persistence/messagesPayload.ts
> -      has_attachments: true
Restored `has_attachments` flag

2023-11-29 09:12 UTC, Vangaorth approved these changes
LGTM

2023-11-29 10:01 UTC, merged