[#176443215,#176443259] API for activation and status of CGN
pagopa/io-dev-api-server pull request #37
Opened 2021-01-25 14:20 UTC by CrisTofani

2021-02-08 17:25 UTC, Undermaken requested changes

2021-02-08 17:25 UTC, Undermaken commented on src/routers/features/cgn/index.ts
> +addHandler(bonusVacanze, "get", addPrefix("/status"), (_, res) => {
```suggestion
addHandler(cgnRouter, "get", addPrefix("/status"), (_, res) => {
```

2021-02-08 17:31 UTC, Undermaken requested changes

2021-02-08 17:31 UTC, Undermaken commented on src/routers/features/cgn/index.ts
> +});
Could it be useful export a [reset](https://github.com/pagopa/io-dev-api-server/blob/2e78da43c0a8c232349906d5a8fec4a3d7f8e5fc/src/routers/features/bdp/index.ts#L193) function to restore the initial state?

https://github.com/pagopa/io-dev-api-server/blob/2e78da43c0a8c232349906d5a8fec4a3d7f8e5fc/src/routers/public.ts#L48

2021-02-09 18:40 UTC, CrisTofani commented on src/routers/features/cgn/index.ts
> +// tslint:disable-next-line:no-commented-code
Since we have multiple definition of `StatusEnum` I just prefer to leave these imports commented to uncomment in case to receive a different payload

2021-02-09 18:56 UTC, merged