chore: [IOBP-804] Added feedback banner mock for the new payment success screen
pagopa/io-dev-api-server pull request #402
Opened 2024-07-31 09:38 UTC by Hantex9

## ⚠️ This PR depends on https://github.com/pagopa/io-services-metadata/pull/821

## Short description
This PR adds the feedback banner definition and its mock. This property is used to show the feedback banner when the user completes a payment successfully with the new payment flow.

## List of changes proposed in this pull request
- Updated content_specs definitions;
- Added `feedbackBanner` properties inside `newPaymentsSection`;

## How to test
Checkout this io-app PR and follow the instructions under the "how to test" section.

2024-10-15 08:46 UTC, hevelius requested changes

2024-10-15 08:46 UTC, hevelius commented on package.json
> +  "content_specs": "https://raw.githubusercontent.com/pagopa/io-services-metadata/IOBP-803-add-banner-new-payment-section/definitions.yml",
It should be update with release version

2024-10-16 15:12 UTC, Hantex9 commented on package.json
> +  "content_specs": "https://raw.githubusercontent.com/pagopa/io-services-metadata/IOBP-803-add-banner-new-payment-section/definitions.yml",
The release version has been addressed into bd181459924c26c45e35e16c4ded5ac6203e10cd

2024-10-22 14:29 UTC, LeleDallas approved these changes

2024-10-22 15:02 UTC, hevelius approved these changes

2024-10-22 15:04 UTC, merged