fix: [SIW-1702] Wrong response to the `POST` request for trial system
pagopa/io-dev-api-server pull request #414
Opened 2024-10-03 09:40 UTC by LazyAfternoons

## Short description
This PR fixes the wrong response to the `POST` request endpoint for the trial system.

## List of changes proposed in this pull request
- Return `404` if a trial id doesn't exists in the configuration of the dev server;
- Return `201` instead of `200` when subscribing; 
- Return 

## How to test
Describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

2024-10-03 10:58 UTC, hevelius requested changes

2024-10-03 10:58 UTC, hevelius commented on src/config.ts
> +    paymentWithValidDueDateCount: 1,
Why also this value is changed?

2024-10-03 10:58 UTC, hevelius commented on src/config.ts
> +    withEUCovidCert: true,
ditto

2024-10-03 16:24 UTC, LazyAfternoons commented on src/config.ts
> +    withEUCovidCert: true,
Unwanted changes, thanks. Removed.

2024-10-04 10:58 UTC, hevelius approved these changes

2024-10-07 13:06 UTC, merged