[IOPID-2093] Parameterization of getSession endpoint
pagopa/io-dev-api-server pull request #417
Opened 2024-10-04 11:09 UTC by Ladirico

## Short description
In order to adapt the changes in the getSession, the possibility of passing parameters was added. 
- If parameters are passed, the getSession returns the required tokens
- In the case where no parameters are passed, getSession returns all the information

## How to test
Run io-app using local environment and follow the instructions of [this PR.](https://github.com/pagopa/io-app/pull/6196)

2024-10-08 07:08 UTC, ChrisMattew approved these changes

2024-10-08 12:39 UTC, shadowsheep1 requested changes

2024-10-08 12:39 UTC, shadowsheep1 commented on src/payloads/session.ts
> +    return tokensObject;
Shouldn't be better here to get the entire payload from `customSession` instead of `tokensObject`. Actually they are the same but if in the future we randomize the SSO Token when we randomize the session token during a fast login refresh, the variable with fresh data'd be `customSession`. Am I right? 
Just treat `tokenObject` as the default initial value. What do you think?
```suggestion
    return customSession;
```

2024-10-08 13:20 UTC, shadowsheep1 requested changes

2024-10-08 13:20 UTC, shadowsheep1 commented on src/payloads/session.ts
> +const tokensObject: PublicSession = {
This was a function to let all SSO token to update during a fast login refresh. Am I right? We should keep that as a function.

2024-10-15 09:10 UTC, Ladirico commented on src/payloads/session.ts
> +    return tokensObject;
I applied the change, it should work now! 🚀

2024-10-17 13:40 UTC, shadowsheep1 approved these changes
LGTM

2024-10-17 13:54 UTC, merged