[IASV-12] Integrate API SiciliaVola
pagopa/io-dev-api-server pull request #60
Opened 2021-07-29 13:07 UTC by debiff

This PR integrates the API needed to manage the IO app SiciliaVola flow. 

In order to maintain the given order, the API are been separated in `secured`, `unsecured` and `auth`.

Note that the swagger `assets/SiciliaVola.yml` it's temporary and will be substituted when will be publicated.

2021-07-29 14:30 UTC, Undermaken requested changes

2021-07-29 14:30 UTC, Undermaken commented on src/routers/features/siciliaVola/secured/index.ts
> +          v => v.idVoucher !== voucherId
Maybe this comparison has no sense: `number | undefined` !== `any` (the body)
Perhaps would you compare two numbers?

```typescript
addHandler(
  securedSvRouter,
  "get",
  addPrefix("/beneficiario/annullaVoucher"),
  (req, res) => {
    const { voucherId } = req.body;
    const maybeVoucherId = t.Integer.decode(voucherId);
    if (maybeVoucherId.isLeft()) {
      // validate the body value
      res.sendStatus(500);
      return;
    }

    if (vouchersBeneficiary.listaRisultati) {
      vouchersBeneficiary = {
        ...vouchersBeneficiary,
        listaRisultati: vouchersBeneficiary.listaRisultati.filter(
          v => v.idVoucher !== maybeVoucherId.value
        )
      };
    }
    res.sendStatus(200);
    return;
  }
);
```

2021-07-29 14:30 UTC, Undermaken commented on src/server.ts
> +  authSvRouter
I don't know if it works, but I guess a router can use other routers. If this works, you could export only a router that includes the 3 specific one

something like
```typescript
export const siciliaVolaRouter = Router();
siciliaVolaRouter.use([unsecuredSvRouter, securedSvRouter, authSvRouter]);
```

2021-07-30 14:45 UTC, debiff commented on src/routers/features/siciliaVola/unsecured/index.ts
> +    const regions = readFileAsJSON(
Thank you! Modified in all the APIs in [ebc4230](https://github.com/pagopa/io-dev-api-server/pull/60/commits/ebc42306499741868fe8043f13873da7443474c4)

2021-07-30 14:45 UTC, debiff commented on src/server.ts
> +  authSvRouter
Modified in [4bcaa71](https://github.com/pagopa/io-dev-api-server/pull/60/commits/4bcaa711a0584dc7936247f19133bdfff137d435)

2021-07-30 14:46 UTC, debiff commented on src/routers/features/siciliaVola/secured/index.ts
> +          v => v.idVoucher !== voucherId
Yes, you're right it's a bug. Fixed in [eab0296](https://github.com/pagopa/io-dev-api-server/pull/60/commits/eab0296bb2b82a03cb5d2275a1b6a944f6fc6fae)

2021-07-30 15:02 UTC, Undermaken requested changes

2021-07-30 15:02 UTC, Undermaken commented on src/routers/features/siciliaVola/auth.ts
> +  res.json({ token: faker.random.uuid() })
```suggestion
  res.json({ token: faker.datatype.uuid() })
```
this is deprecated ([I realized it just minutes ago](https://github.com/pagopa/io-dev-api-server/commit/579e19e6864e1df01ce69fcaa5872c888b18afd9#))

2021-07-30 15:03 UTC, Undermaken commented on src/routers/features/siciliaVola/auth.ts
> +  res.json({ token: faker.random.uuid() })
@debiff fyi
I committed this change

2021-07-30 15:09 UTC, Undermaken approved these changes

2021-07-30 15:09 UTC, merged