[IARS-46] Add the support to special services and service category
pagopa/io-dev-api-server pull request #87
Opened 2021-11-03 15:37 UTC by CrisTofani

This PR introduces the support services' categories.

`getServices` and related functions to include services like SiciliaVola on the services list construction has been refactored to better include special services on future releases.

2021-11-04 09:33 UTC, Undermaken requested changes

2021-11-04 09:33 UTC, Undermaken commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
I believe this approach could not scale. We should manually increase the counter.
Furthermore `organizationsCount` is only used as size, could be used `nationalLocalServices.length` instead?

My suggestion is based on an array of tuple where the first element is the flag and the second element is the service factory

```typescript
  const specialServices: ReadonlyArray<readonly [
    boolean,
    (orgCount: number) => ServicePublic
  ]> = [
    [ioDevServerConfig.services.includeSiciliaVola, withSiciliaVolaService],
    [ioDevServerConfig.services.includeCgn, withCgnService]
  ];

  // eventually add the special services based on config flag
  return specialServices.reduce((acc, curr) => {
    if (curr[0]) {
      return [...acc, curr[1](acc.length)];
    }
    return acc;
  }, nationalLocalServices);
```
note `specialServices` could be a const outside this function

2021-11-05 09:30 UTC, CrisTofani commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
@Undermaken Good point, this is absolutely a smarter way to include more "special" services on future. I propose another small refactoring on folder structure/file organization. Since I imagine special services may increase on future I think we can reorganize services in this way:
- `payloads/services` <-- this is the main folder
- `payloads/services/index.ts` <-- the current `service.ts`
- `payloads/services/special.ts` <-- here we collect the special services implementation
- `payloads/services/optional.ts` <-- when and if it will be needed we can introduce them here

What do you think?

2021-11-05 10:30 UTC, CrisTofani commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
6687b11 includes the proposed refactoring

2021-11-05 18:05 UTC, Undermaken commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
I believe it is an improvement!
I just done a commit https://github.com/pagopa/io-dev-api-server/pull/87/commits/d299326f5c2eb6c8364f6daf108620960efc9e54 with some refactoring (renaming and moving some functions) and yes, you were right (and I was wrong) when you used the `Set` to compute how many organizations are in the service!
Could you check if it is good?

Anyway should we merge this PR when the new io-backend spec will be officially deployed?

2021-11-05 18:09 UTC, CrisTofani commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
Yes I think it's better to wait since the api spec may need some rework. 

Talking about the Set, yes we may have more services than organizations 🙈 just forgot about that when I accepted your suggestion

2021-11-05 18:14 UTC, Undermaken commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
I did another round of refactoring 
https://github.com/pagopa/io-dev-api-server/pull/87/commits/9bbe9a71f08648f1c2139f1aa0626926404f73f9
Double check when you can

2021-11-08 09:18 UTC, CrisTofani commented on src/payloads/service.ts
> +  return nationalLocalServices.concat(
LGTM whenever the API spec is froze we can merge this PR

2021-12-13 08:40 UTC, pietro909 commented
@Undermaken @CrisTofani can we merge it?

2021-12-13 08:41 UTC, pietro909 commented on package.json
> +  "api_backend_specs": "https://raw.githubusercontent.com/pagopa/io-backend/special-service-specs/api_backend.yaml",
time to point to `7.26.0` 😃

2021-12-13 08:42 UTC, CrisTofani commented on package.json
> +  "api_public_specs": "https://raw.githubusercontent.com/pagopa/io-backend/special-service-specs/api_public.yaml",
```suggestion
  "api_backend_specs": "https://raw.githubusercontent.com/pagopa/io-backend/v7.26.0-RELEASE/api_backend.yaml",
  "api_public_specs": "https://raw.githubusercontent.com/pagopa/io-backend/v7.26.0-RELEASE/api_public.yaml",
```

2021-12-13 08:42 UTC, CrisTofani commented on package.json
> +  "api_backend_specs": "https://raw.githubusercontent.com/pagopa/io-backend/special-service-specs/api_backend.yaml",
I was just changing it ca074d6 😄

2021-12-13 08:43 UTC, CrisTofani commented on package.json
> +  "api_backend_specs": "https://raw.githubusercontent.com/pagopa/io-backend/special-service-specs/api_backend.yaml",
We can now merge this

2021-12-13 08:44 UTC, Undermaken approved these changes

2021-12-13 08:45 UTC, merged