Support payment config
pagopa/io-dev-api-server pull request #90
Opened 2021-11-05 18:42 UTC by pietro909

The new config under `wallet.payment` is defined [here](https://github.com/pagopa/io-dev-api-server/compare/IAI-85-payment-config?expand=1#diff-fea291e6a68bacafef88ed99be7ad4916267ab6585b42401f1f76ddcbb37706aR52). 

It will allow us to test the full payment journey with deterministic values.

2021-11-05 21:03 UTC, Undermaken requested changes

2021-11-05 21:03 UTC, Undermaken commented on src/payloads/payload.ts
> +    }) as PaymentRequestsGetResponse["importoSingoloVersamento"]),
```suggestion
  getRandomValue(
    ioDevServerConfig.wallet.payment?.amount,
    faker.datatype.number({
      min: 1,
      max: 9999
    }),
    "wallet"
  ) as ImportoEuroCents,
```
you could use `getRandomValue` function to take advantage of randomness control (for each section)
If you find it as a good idea, [this function](https://github.com/pagopa/io-dev-api-server/blob/1a047b5f5c88ebf8c2720380fc5ec453fb771f4a/src/utils/random.ts#L13) should be changed

from this
```
const getValueGlobalRandomOn: RandomValueFunc = <T>(
  defaultValue: T,
  randomValue: T,
  configSectionKey: AllorRandomValueKeys
) =>
  ioDevServerConfig[configSectionKey].allowRandomValues
    ? randomValue
    : defaultValue;
```
to this
```typescript
const getValueGlobalRandomOn: RandomValueFunc = <T>(
  defaultValue: T,
  randomValue: T,
  configSectionKey: AllorRandomValueKeys
): T =>
  ioDevServerConfig[configSectionKey].allowRandomValues ||
  defaultValue === undefined
    ? randomValue
    : defaultValue;
```

2021-11-08 08:35 UTC, pietro909 commented on src/payloads/payload.ts
> +    }) as PaymentRequestsGetResponse["importoSingoloVersamento"]),
Addressed in 1f8270f

2021-11-08 08:35 UTC, pietro909 commented on src/types/config.ts
> +      payment: PaymentConfig
Good point, see 1f8270f

2021-11-08 18:08 UTC, Undermaken approved these changes

2021-11-08 18:08 UTC, merged