Fix small pagination issue and add config for live mode
pagopa/io-dev-api-server pull request #94
Opened 2021-11-19 16:58 UTC by pietro909

2021-11-20 16:05 UTC, Undermaken requested changes

2021-11-20 16:05 UTC, Undermaken commented on src/types/config.ts
> +  interval: t.number,
```suggestion
  interval: Millisecond,
```
you could use a type that already describes the used unit of measure
`import { Millisecond } from "@pagopa/ts-commons/lib/units";`

2021-11-22 08:31 UTC, pietro909 commented on src/types/config.ts
> +  interval: t.number,
I'm getting:

> TS2693: 'Millisecond' only refers to a type, but is being used as a value here.

I may be mixing up things here.

2021-11-22 09:59 UTC, Undermaken commented on src/types/config.ts
> +  interval: t.number,
this is my bad suggestion!
I thought it is a codec/type
Forget it. Sorry

2021-11-22 13:33 UTC, Undermaken approved these changes

2021-11-22 13:34 UTC, merged