Add medical message with attachments and SVG
pagopa/io-dev-api-server pull request #98
Opened 2021-11-29 18:53 UTC by pietro909

The new message sends attachments with a barcode which should mimick what we expect to see in the wild:

![Screenshot 2021-11-29 at 18 19 35](https://user-images.githubusercontent.com/2094604/143926002-7bbf0618-b5ce-4d37-9ac0-aef6ef61d055.png)

2021-11-30 08:19 UTC, Undermaken requested changes

2021-11-30 08:19 UTC, Undermaken commented on src/routers/message.ts
> +              "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MiIgaGVpZ2h0PSIxMDQiIHZlcnNpb249IjEuMSI+DQogIDxsaW5lIHN0cm9rZS13aWR0aD0iNiIgc3Ryb2tlPSIjMDAwIiB4MT0iMCIgeTE9IjAiIHgyPSIw
To avoid long content inside the code and to change the svg image easily, what do you think about this approach we recently introduced?

https://github.com/pagopa/io-dev-api-server/blob/142ec24054bf64d8c357e755a316b605a2faafc9/src/payloads/features/bonus-vacanze/bonus.ts#L12

2021-11-30 17:17 UTC, pietro909 commented on src/routers/message.ts
> +              "PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI1MiIgaGVpZ2h0PSIxMDQiIHZlcnNpb249IjEuMSI+DQogIDxsaW5lIHN0cm9rZS13aWR0aD0iNiIgc3Ryb2tlPSIjMDAwIiB4MT0iMCIgeTE9IjAiIHgyPSIw
Much better indeed 🎉  https://github.com/pagopa/io-dev-api-server/pull/98/files#diff-c4cdb7cf0e69ecfc696d0ba80b8411dd4297658be4a57dad5f0954d7a9ae6d74R130

2021-11-30 17:30 UTC, Undermaken requested changes

2021-12-01 09:41 UTC, pietro909 commented on src/routers/message.ts
> +    } as any);
Totally fine with it.

2021-12-01 10:00 UTC, Undermaken commented on src/routers/message.ts
> +    } as any);
@pietro909 if you want, I can push that commit (it has been done in a mine custom branch)

2021-12-01 13:36 UTC, pietro909 commented on src/routers/message.ts
> +    } as any);
I thought you already did in that commit. I saw now that is in a different branch 😅 
Please be my guest :-)

2021-12-01 16:09 UTC, merged